### ISSUE TITLE
Question: will the two kinds of Dev-Portals content-wise be compatible?

### ISSUE THREAD

**Issue by AnRei123** [Azure/API-Portal#10]
Great to see this new project! I am looking forward to the possibilities this might offer. 

Here my questions:
1) I wonder if the two kind of DevPortal frameworks, this new Azure API-Portal and the already existing new Azure DevPortal will be compatible in regard to the web contents that are stored in the data/content.json files. This would be very important to us that we would not need to build up the contents and styles in two portals separately and in parallel. What is the current status quo here? And if this is currently not the case - will there be an automated migration path supported? Thank you very much in advance.
2) Is it only supported to host the API-Portal websites in the Intranet or is it also possible to deploy the websites as an application package locally? 
I wonder if this framework would allow us to provide a local portal solution to our customers to install it locally on their PCs or virtualized environment. The idea would be that we could provide it together with another installation package that the user would get from us and that we are able to update API specification on demand via the Intranet automatically at any time. Is this use case already be supported by this framework? Or do you plan it?

**Comment by azaslonov** [comment]
Hi @AnRei123,

> wonder if the two kind of DevPortal frameworks, this new Azure API-Portal and the already existing new Azure DevPortal will be compatible in regard to the web contents that are stored in the data/content.json files. This would be very important to us that we would not need to build up the contents and styles in two portals separately and in parallel. What is the current status quo here? And if this is currently not the case - will there be an automated migration path supported? Thank you very much in advance.

Right, internally they use the same format, only import/export functionality needs to be unified (through additional options probably), so you'll be able to move the content between both projects seamlessly. I'll do that soon.

> Is it only supported to host the API-Portal websites in the Intranet or is it also possible to deploy the websites as an application package locally?
> I wonder if this framework would allow us to provide a local portal solution to our customers to install it locally on their PCs or virtualized environment. The idea would be that we could provide it together with another installation package that the user would get from us and that we are able to update API specification on demand via the Intranet automatically at any time. Is this use case already be supported by this framework? Or do you plan it?

Yes, Angelika, I think this particular scenario you will be able to address. We can work together to shape it out properly.

**Comment by AnRei123** [comment]
Ok, sounds good.

**Comment by azaslonov** [comment]
I guess we can close this issue, since answers provided.
