### ISSUE TITLE
Clarify development path compared to self-hosted version

### ISSUE THREAD

**Issue by erwinkramer** [Azure/API-Portal#16]
We now have 2 versions of the portal code base with some slight differences: 
- https://github.com/Azure/api-management-developer-portal
- https://github.com/Azure/API-Portal

This brings some questions:
- Will this API-Portal replace the other one eventually? This is important to know, because if you've setup the self-hosted one with the https://github.com/Azure/api-management-developer-portal and some devops pipelines, there doesn't seem to be much reason to move away.
- Will the 2 versions have separate development and features eventually? Apart from the way you can release it, there doesn't seem to be much difference yet.

**Comment by azaslonov** [comment]
Hi @erwinkramer,

No, it won't replace the developer portal, but surely they will share a lot of common parts.

The idea of this project (@mikebudzynski can correct me) is to have a portal, disconnected from specific API management providers (like Azure API Management or Apigee). At the same time, the consumers could enable support for those providers (if they want to) as simple as installing another "connector" npm package. By default (basically, as it is now), it would have the "file system connector" which reads/writes API specs and content from/to the file system.

Of course, we're not there yet, so I'll take some time to unify flows and make the functionality pluggable. Then, when it's all done, we may think of merging these two projects.

**Comment by erwinkramer** [comment]
Thanks, makes sense.

**Comment by mikebudzynski** [comment]
@erwinkramer, as @azaslonov mentioned, the API Portal is disconnected from any API management solution. The API Management's developer portal is built into Azure API Management and uses it for additional functionality, like user and identity management. They do share most of the underlying codebase, but serve different purposes.
