### ISSUE TITLE
openApi docs added - No operations found

### ISSUE THREAD

**Issue by seanksullivan** [Azure/API-Portal#18]
Looking at this repo briefly (forgive me if I missed something)

If I add a new, valid openApi json (ver. 3.0.1) file to the api-specs folder, the API will be listed on the home page, but will not display operations within: "No operations found".

The three 'sample' json files work and display as expected.  What am I missing?

**Stack trace:**
Unable to process binding "if: function(){return operations }"
Message: Unable to process binding "foreach: function(){return { data:operations,as:'item'} }"
Message: Unable to process binding "attr: function(){return { href:$component.getReferenceUrl(item)} }"
Message: Parameter "operationName" not specified

**Comment by azaslonov** [comment]
Hi @seanksullivan, might be a bug, do you mind sending your file (redacted if needed) to alzaslon@microsoft.com?

**Comment by seanksullivan** [comment]
Our Swashbuckle.AspNetCore generated openApi docs do not contain any operationId name/values, which appear to be expected.

**Comment by seanksullivan** [comment]
Interesting... Swashbuckle.AspNetCore omits the operationId by default.
https://github.com/domaindrivendev/Swashbuckle.AspNetCore#assign-explicit-operationids

It appears that operationId is not required within an openApi doc.

**Comment by azaslonov** [comment]
Fixed. Thanks for the details!
